name: Deploy Static Site to Azure Web App - orchvate-updates

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2630DFEB9E5B40B3A5D41087B44254BB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0DF30BCBC6B4C01BF498072B4010243 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2986BF940EF64AA89DAEB68242660C04 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: orchvate-updates
          package: .
